name: Update Current Project
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: jacklebeignet/jacklebeignet
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Find most recently updated repo
        id: find-repo
        run: |
          MOST_RECENT_REPO=$(gh repo list jacklebeignet --limit 1 --json nameWithOwner,updatedAt --jq 'sort_by(.updatedAt) | reverse | .[0].nameWithOwner')
          echo "most_recent_repo=$MOST_RECENT_REPO" >> $GITHUB_OUTPUT
          REPO_NAME=$(echo "$MOST_RECENT_REPO" | cut -d'/' -f2)
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Debug - Show current README content
        run: |
          echo "=== CURRENT README CONTENT ==="
          cat README.md
          echo "============================"

      - name: Update README
        run: |
          # First try with markdown link format
          sed -i -E "s|I'm currently working on \[.*\]\(.*\)|I'm currently working on [${{ steps.find-repo.outputs.repo_name }}](https://github.com/${{ steps.find-repo.outputs.most_recent_repo }})|" README.md || \
          # If that fails, try without link format
          sed -i -E "s|I'm currently working on .*|I'm currently working on [${{ steps.find-repo.outputs.repo_name }}](https://github.com/${{ steps.find-repo.outputs.most_recent_repo }})|" README.md

          echo "=== MODIFIED README CONTENT ==="
          cat README.md
          echo "=============================="

      - name: Debug - Show git changes
        run: |
          echo "=== GIT STATUS ==="
          git status
          echo "=== GIT DIFF ==="
          git diff
          echo "================"

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "🔄 Update current project to ${{ steps.find-repo.outputs.repo_name }}" || echo "No changes to commit"
          git push
