name: Update "Currently Working On" with latest repo

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update currently working on repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update "currently working on" line
        uses: actions/github-script@v6
        with:
          script: |
            const username = 'jacklebeignet';
            const readmePath = 'README.md';

            const events = await github.rest.activity.listPublicEventsForUser({
              username,
              per_page: 10,
            });

            const pushEvent = events.data.find(e => e.type === 'PushEvent');
            if (!pushEvent) {
              console.log('No push event found');
              return;
            }

            const repoName = pushEvent.repo.name; // e.g. jacklebeignet/scripts
            const repoShort = repoName.split('/')[1];
            const repoUrl = `https://github.com/${repoName}`;
            const newLine = `🔭 I’m currently working on [${repoShort}](${repoUrl})`;

            const fs = require('fs');
            const readme = fs.readFileSync(readmePath, 'utf8');

            const updated = readme.replace(
              /🔭 I’m currently working on.*(\n)?/,
              newLine + '\n'
            );

            fs.writeFileSync(readmePath, updated);

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🔄 Update current project to latest repo" || echo "Nothing to commit"
          git push
