name: Update Current Project
on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile README
        uses: actions/checkout@v4
        with:
          repository: jacklebeignet/jacklebeignet
          path: profile-readme
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Find most recently updated repo
        id: find-repo
        run: |
          # Get list of all repositories sorted by most recently updated
          MOST_RECENT_REPO=$(gh repo list jacklebeignet --limit 1 --json nameWithOwner,updatedAt --jq 'sort_by(.updatedAt) | reverse | .[0].nameWithOwner')
          echo "most_recent_repo=$MOST_RECENT_REPO" >> $GITHUB_OUTPUT

          # Extract just the repo name (without owner)
          REPO_NAME=$(echo "$MOST_RECENT_REPO" | cut -d'/' -f2)
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Update README
        working-directory: ./profile-readme
        run: |
          # Format the replacement text
          REPLACEMENT_TEXT="I'm currently working on [${{ steps.find-repo.outputs.repo_name }}](https://github.com/${{ steps.find-repo.outputs.most_recent_repo }})"
          
          # Debug output
          echo "Replacement text will be: $REPLACEMENT_TEXT"
          
          # Update the README.md file
          sed -i -E "s|I'm currently working on \[.*\]|$REPLACEMENT_TEXT|" README.md

      - name: Commit changes
        working-directory: ./profile-readme
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "🔄 Update current project to ${{ steps.find-repo.outputs.repo_name }}" || echo "No changes to commit"
          git push
